"""The 100-app research set from the assignment, plus official-doc seeds.

Seeds are starting points, not answers. The fetch step records what each URL
actually returned. A URL that 404s is dropped before any claim is made.
"""

from __future__ import annotations

CATEGORIES = [
    {"id": "crm", "name": "CRM and Sales", "range": "1–10"},
    {"id": "support", "name": "Support and Helpdesk", "range": "11–20"},
    {"id": "comms", "name": "Communications and Messaging", "range": "21–30"},
    {"id": "marketing", "name": "Marketing, Ads, Email and Social", "range": "31–40"},
    {"id": "ecom", "name": "Ecommerce", "range": "41–50"},
    {"id": "data", "name": "Data, SEO and Scraping", "range": "51–60"},
    {"id": "dev", "name": "Developer, Infra and Data platforms", "range": "61–70"},
    {"id": "productivity", "name": "Productivity and Project Management", "range": "71–80"},
    {"id": "finance", "name": "Finance and Fintech", "range": "81–90"},
    {"id": "ai", "name": "AI, Research and Media-native", "range": "91–100"},
]


def _app(i, name, cat, website, hint, queries, urls):
    return {
        "id": i,
        "app_name": name,
        "category_id": cat,
        "website": website,
        "hint": hint,
        "search_queries": queries,
        "seed_urls": urls,
    }


APPS = [
    _app(1, "Salesforce", "crm", "https://www.salesforce.com", "salesforce.com",
         ["Salesforce REST API OAuth authentication developer documentation"],
         [
             "https://developer.salesforce.com/docs/atlas.en-us.api_rest.meta/api_rest/intro_what_is_rest_api.htm",
             "https://developer.salesforce.com/docs/atlas.en-us.api_rest.meta/api_rest/intro_understanding_authentication.htm",
             "https://developer.salesforce.com/docs/atlas.en-us.api_rest.meta/api_rest/quickstart_oauth.htm",
         ]),
    _app(2, "HubSpot", "crm", "https://www.hubspot.com", "hubspot.com",
         ["HubSpot API authentication OAuth private app developer docs"],
         [
             "https://developers.hubspot.com/docs/guides/apps/authentication/intro-to-auth",
             "https://developers.hubspot.com/docs/guides/api/overview",
             "https://developers.hubspot.com/docs/api/private-apps",
         ]),
    _app(3, "Pipedrive", "crm", "https://www.pipedrive.com", "pipedrive.com",
         ["Pipedrive API authentication API token OAuth documentation"],
         [
             "https://developers.pipedrive.com/docs/api/v1",
             "https://pipedrive.readme.io/docs/core-api-concepts-authentication",
             "https://developers.pipedrive.com/docs/api/v1/Getting-started",
         ]),
    _app(4, "Attio", "crm", "https://attio.com", "attio.com",
         ["Attio API authentication developer documentation"],
         [
             "https://docs.attio.com/rest-api/overview",
             "https://developers.attio.com/docs/overview",
             "https://docs.attio.com/docs/overview",
         ]),
    _app(5, "Twenty", "crm", "https://twenty.com", "twenty.com",
         ["Twenty CRM API authentication REST GraphQL documentation"],
         [
             "https://docs.twenty.com/developers/api-and-webhooks/api",
             "https://twenty.com/developers/section/api",
             "https://docs.twenty.com/developers/extend/capabilities/apis",
         ]),
    _app(6, "Podio", "crm", "https://www.podio.com", "podio.com",
         ["Podio API OAuth authentication developer documentation"],
         [
             "https://developers.podio.com/authentication",
             "https://developers.podio.com/doc",
         ]),
    _app(7, "Zoho CRM", "crm", "https://www.zoho.com/crm/", "zoho.com/crm",
         ["Zoho CRM API OAuth authentication documentation"],
         [
             "https://www.zoho.com/crm/developer/docs/api/v8/oauth-overview.html",
             "https://www.zoho.com/crm/developer/docs/api/v2/auth-request.html",
             "https://www.zoho.com/crm/developer/docs/api/v8/",
         ]),
    _app(8, "Close", "crm", "https://close.com", "close.com",
         ["Close CRM API authentication documentation"],
         [
             "https://developer.close.com/",
             "https://developer.close.com/topics/authentication/",
             "https://help.close.com/docs/api-keys",
         ]),
    _app(9, "Copper", "crm", "https://www.copper.com", "copper.com",
         ["Copper CRM API authentication developer documentation"],
         [
             "https://developer.copper.com/introduction/authentication.html",
             "https://developer.copper.com/",
             "https://developer.copper.com/introduction/requests.html",
         ]),
    _app(10, "DealCloud", "crm", "https://www.intapp.com/dealcloud/", "api.docs.dealcloud.com",
          ["DealCloud API OAuth authentication documentation"],
          [
              "https://api.docs.dealcloud.com/docs/token",
              "https://api.docs.dealcloud.com/docs",
              "https://api.docs.dealcloud.com/",
          ]),
    _app(11, "Zendesk", "support", "https://www.zendesk.com", "zendesk.com",
          ["Zendesk API authentication OAuth API token documentation"],
          [
              "https://developer.zendesk.com/api-reference/introduction/security-and-auth/",
              "https://developer.zendesk.com/api-reference/ticketing/introduction/",
              "https://support.zendesk.com/hc/en-us/articles/4408889192858-Managing-access-to-the-Zendesk-API",
          ]),
    _app(12, "Intercom", "support", "https://www.intercom.com", "intercom.com",
          ["Intercom API authentication developer documentation"],
          [
              "https://developers.intercom.com/docs/build-an-integration/learn-more/authentication",
              "https://developers.intercom.com/docs/references/introduction",
          ]),
    _app(13, "Freshdesk", "support", "https://www.freshworks.com/freshdesk/", "freshdesk.com",
          ["Freshdesk API authentication API key documentation"],
          [
              "https://developers.freshdesk.com/api/#authentication",
              "https://developers.freshworks.com/docs/freshdesk/api/#authentication",
              "https://support.freshdesk.com/support/solutions/articles/225435-how-to-find-your-api-key",
          ]),
    _app(14, "Front", "support", "https://front.com", "front.com",
          ["Front API authentication developer documentation"],
          [
              "https://dev.frontapp.com/docs/authentication",
              "https://dev.frontapp.com/reference/introduction",
          ]),
    _app(15, "Pylon", "support", "https://www.usepylon.com", "usepylon.com",
          ["Pylon usepylon API MCP authentication documentation"],
          [
              "https://www.usepylon.com/integrations/mcp",
              "https://support.usepylon.com/articles/2407390554-connecting-to-the-pylon-mcp-server",
              "https://docs.usepylon.com/",
          ]),
    _app(16, "LiveAgent", "support", "https://www.liveagent.com", "liveagent.com",
          ["LiveAgent API v3 authentication API key documentation"],
          [
              "https://support.liveagent.com/741982-API-key",
              "https://support.liveagent.com/567924-Documentation--examples",
              "https://www.liveagent.com/api/",
          ]),
    _app(17, "Plain", "support", "https://www.plain.com", "plain.com",
          ["Plain.com GraphQL API authentication documentation"],
          [
              "https://www.plain.com/docs/graphql/authentication",
              "https://www.plain.com/docs/graphql/introduction",
          ]),
    _app(18, "Help Scout", "support", "https://www.helpscout.com", "helpscout.com",
          ["Help Scout Mailbox API authentication documentation"],
          [
              "https://developer.helpscout.com/mailbox-api/overview/authentication/",
              "https://developer.helpscout.com/mailbox-api/",
          ]),
    _app(19, "Gorgias", "support", "https://www.gorgias.com", "gorgias.com",
          ["Gorgias API authentication documentation"],
          [
              "https://developers.gorgias.com/reference/authentication",
              "https://developers.gorgias.com/docs/authentication",
              "https://developers.gorgias.com/",
          ]),
    _app(20, "Gladly", "support", "https://www.gladly.com", "gladly.com",
          ["Gladly REST API authentication documentation"],
          [
              "https://developer.gladly.com/rest/",
              "https://developer.gladly.com/",
          ]),
    _app(21, "Slack", "comms", "https://slack.com", "slack.com",
          ["Slack API authentication OAuth MCP documentation"],
          [
              "https://api.slack.com/authentication",
              "https://api.slack.com/authentication/token-types",
              "https://docs.slack.dev/ai/slack-mcp-server",
          ]),
    _app(22, "Twilio", "comms", "https://www.twilio.com", "twilio.com",
          ["Twilio API authentication documentation"],
          [
              "https://www.twilio.com/docs/usage/requests-to-twilio",
              "https://www.twilio.com/docs/iam/api-keys",
              "https://www.twilio.com/docs/usage/api",
          ]),
    _app(23, "Zoho Cliq", "comms", "https://www.zoho.com/cliq/", "zoho.com/cliq",
          ["Zoho Cliq REST API authentication documentation"],
          [
              "https://www.zoho.com/cliq/help/restapi/v2/",
              "https://www.zoho.com/cliq/help/restapi/v2/#Authorization",
          ]),
    _app(24, "Lark", "comms", "https://www.larksuite.com", "open.larksuite.com",
          ["Larksuite open platform API authentication tenant access token"],
          [
              "https://open.larksuite.com/document/home/introduction",
              "https://open.larksuite.com/document/ukTMukTMukTM/ukDNz4SO0MjL5QzM/auth-v3/auth/tenant_access_token_internal",
              "https://open.larksuite.com/document/server-docs/getting-started/api-access-token/auth-v3/tenant_access_token_internal",
          ]),
    _app(25, "Pumble", "comms", "https://pumble.com", "pumble.com",
          ["Pumble API keys authentication official documentation"],
          [
              "https://pumble.com/api",
              "https://pumble.com/help/integrations/",
              "https://www.pumble.com/",
          ]),
    _app(26, "Discord", "comms", "https://discord.com", "discord.com",
          ["Discord API authentication bot token OAuth documentation"],
          [
              "https://discord.com/developers/docs/getting-started",
              "https://discord.com/developers/docs/topics/oauth2",
              "https://discord.com/developers/docs/reference",
          ]),
    _app(27, "Telegram", "comms", "https://telegram.org", "core.telegram.org",
          ["Telegram Bot API authentication token documentation"],
          [
              "https://core.telegram.org/bots/api",
              "https://core.telegram.org/bots",
              "https://core.telegram.org/bots/api#authorizing-your-bot",
          ]),
    _app(28, "WhatsApp Business", "comms", "https://business.whatsapp.com", "developers.facebook.com/docs/whatsapp",
          ["WhatsApp Cloud API get started authentication documentation"],
          [
              "https://developers.facebook.com/docs/whatsapp/cloud-api/get-started",
              "https://developers.facebook.com/docs/whatsapp/business-management-api/get-started",
              "https://developers.facebook.com/docs/whatsapp",
          ]),
    _app(29, "Aircall", "comms", "https://aircall.io", "aircall.io",
          ["Aircall API authentication documentation"],
          [
              "https://developer.aircall.io/api-references/",
              "https://developer.aircall.io/tutorials/basic-authentication",
              "https://developer.aircall.io/",
          ]),
    _app(30, "Vonage", "comms", "https://www.vonage.com", "developer.vonage.com",
          ["Vonage API authentication documentation"],
          [
              "https://developer.vonage.com/en/getting-started/concepts/authentication",
              "https://developer.vonage.com/en/api",
          ]),
    _app(31, "Google Ads", "marketing", "https://ads.google.com", "developers.google.com/google-ads",
          ["Google Ads API OAuth developer token documentation"],
          [
              "https://developers.google.com/google-ads/api/docs/oauth/overview",
              "https://developers.google.com/google-ads/api/docs/get-started/dev-token",
              "https://developers.google.com/google-ads/api/docs/start",
          ]),
    _app(32, "Meta Ads", "marketing", "https://www.facebook.com/business/ads", "developers.facebook.com/docs/marketing-apis",
          ["Meta Marketing API authentication get started documentation"],
          [
              "https://developers.facebook.com/docs/marketing-api/get-started",
              "https://developers.facebook.com/docs/marketing-apis",
              "https://developers.facebook.com/docs/marketing-api/overview",
          ]),
    _app(33, "LinkedIn Ads", "marketing", "https://business.linkedin.com/advertise", "learn.microsoft.com/linkedin/marketing",
          ["LinkedIn Marketing API access authentication documentation"],
          [
              "https://learn.microsoft.com/en-us/linkedin/marketing/integrations/ads/getting-started",
              "https://learn.microsoft.com/en-us/linkedin/shared/authentication/authentication",
              "https://learn.microsoft.com/en-us/linkedin/marketing/getting-started",
          ]),
    _app(34, "GoHighLevel", "marketing", "https://www.gohighlevel.com", "highlevel.stoplight.io",
          ["GoHighLevel HighLevel API authentication OAuth private integration token"],
          [
              "https://marketplace.gohighlevel.com/docs/",
              "https://highlevel.stoplight.io/docs/integrations/0443d7d1a4bd0-overview",
              "https://help.gohighlevel.com/support/solutions/articles/48001060529-highlevel-api",
          ]),
    _app(35, "Mailchimp", "marketing", "https://mailchimp.com", "mailchimp.com/developer",
          ["Mailchimp Marketing API authentication OAuth API key documentation"],
          [
              "https://mailchimp.com/developer/marketing/guides/access-user-data-with-oauth-2/",
              "https://mailchimp.com/developer/marketing/guides/quick-start/",
              "https://mailchimp.com/developer/marketing/api/",
          ]),
    _app(36, "Klaviyo", "marketing", "https://www.klaviyo.com", "developers.klaviyo.com",
          ["Klaviyo API authentication private key OAuth documentation"],
          [
              "https://developers.klaviyo.com/en/docs/authenticate_",
              "https://developers.klaviyo.com/en/reference/api_overview",
          ]),
    _app(37, "systeme.io", "marketing", "https://systeme.io", "systeme.io",
          ["systeme.io public API authentication documentation"],
          [
              "https://developer.systeme.io/reference/api",
              "https://developer.systeme.io/",
              "https://api.systeme.io/documentation",
          ]),
    _app(38, "Pinterest", "marketing", "https://www.pinterest.com", "developers.pinterest.com",
          ["Pinterest API authentication documentation"],
          [
              "https://developers.pinterest.com/docs/getting-started/authentication/",
              "https://developers.pinterest.com/docs/getting-started/introduction/",
          ]),
    _app(39, "Threads", "marketing", "https://www.threads.net", "developers.facebook.com/docs/threads",
          ["Threads API Meta get started authentication documentation"],
          [
              "https://developers.facebook.com/docs/threads/get-started",
              "https://developers.facebook.com/docs/threads",
          ]),
    _app(40, "SendGrid", "marketing", "https://sendgrid.com", "sendgrid.com",
          ["SendGrid API authentication API key documentation"],
          [
              "https://www.twilio.com/docs/sendgrid/api-reference/how-to-use-the-sendgrid-v3-api/authentication",
              "https://www.twilio.com/docs/sendgrid/for-developers/sending-email/api-getting-started",
              "https://docs.sendgrid.com/api-reference/how-to-use-the-sendgrid-v3-api/authentication",
          ]),
    _app(41, "Shopify", "ecom", "https://www.shopify.com", "shopify.dev",
          ["Shopify Admin API authentication OAuth documentation"],
          [
              "https://shopify.dev/docs/apps/build/authentication-authorization",
              "https://shopify.dev/docs/api/admin-rest",
              "https://shopify.dev/docs/api/usage/authentication",
          ]),
    _app(42, "WooCommerce", "ecom", "https://woocommerce.com", "woocommerce.com/document/woocommerce-rest-api",
          ["WooCommerce REST API authentication documentation"],
          [
              "https://woocommerce.github.io/woocommerce-rest-api-docs/#authentication",
              "https://developer.woocommerce.com/docs/getting-started-with-the-woocommerce-rest-api/",
          ]),
    _app(43, "BigCommerce", "ecom", "https://www.bigcommerce.com", "developer.bigcommerce.com",
          ["BigCommerce API authentication documentation"],
          [
              "https://developer.bigcommerce.com/docs/start/authentication",
              "https://developer.bigcommerce.com/docs/start/authentication/deep-dive",
          ]),
    _app(44, "Salesforce Commerce Cloud", "ecom", "https://www.salesforce.com/products/commerce/", "developer.salesforce.com/docs/commerce",
          ["Salesforce Commerce Cloud SCAPI OCAPI authorization documentation"],
          [
              "https://developer.salesforce.com/docs/commerce/commerce-api/guide/authorization.html",
              "https://developer.salesforce.com/docs/commerce/b2c-commerce/guide/b2c-developer-authentication.html",
              "https://developer.salesforce.com/docs/commerce/commerce-api/guide/get-started.html",
          ]),
    _app(45, "Magento", "ecom", "https://business.adobe.com/products/magento/magento-commerce.html", "developer.adobe.com/commerce",
          ["Adobe Commerce Magento web API token authentication documentation"],
          [
              "https://developer.adobe.com/commerce/webapi/get-started/authentication/",
              "https://developer.adobe.com/commerce/webapi/get-started/authentication/gs-authentication-token/",
              "https://developer.adobe.com/commerce/webapi/rest/use-rest/authentication/",
          ]),
    _app(46, "Squarespace", "ecom", "https://www.squarespace.com", "developers.squarespace.com",
          ["Squarespace Commerce API authentication documentation"],
          [
              "https://developers.squarespace.com/commerce-apis/authentication",
              "https://developers.squarespace.com/commerce-apis/overview",
          ]),
    _app(47, "Ecwid", "ecom", "https://www.ecwid.com", "api-docs.ecwid.com",
          ["Ecwid API authentication documentation"],
          [
              "https://docs.ecwid.com/authentication",
              "https://api-docs.ecwid.com/reference/authentication",
              "https://docs.ecwid.com/",
          ]),
    _app(48, "Gumroad", "ecom", "https://gumroad.com", "gumroad.com/api",
          ["Gumroad API authentication documentation"],
          [
              "https://gumroad.com/api",
              "https://app.gumroad.com/api",
              "https://gumroad.com/api#authentication",
          ]),
    _app(49, "Amazon Selling Partner", "ecom", "https://developer.amazonservices.com", "developer-docs.amazon.com/sp-api",
          ["Amazon Selling Partner API authentication registration documentation"],
          [
              "https://developer-docs.amazon.com/sp-api/docs/connecting-to-the-selling-partner-api",
              "https://developer-docs.amazon.com/sp-api/docs/registering-your-application",
              "https://developer-docs.amazon.com/sp-api/docs/sp-api-registration-overview",
          ]),
    _app(50, "fanbasis", "ecom", "https://www.fanbasis.com", "fanbasis.com",
          ["fanbasis API documentation authentication developer"],
          [
              "https://www.fanbasis.com/",
              "https://docs.fanbasis.com/",
              "https://developer.fanbasis.com/",
              "https://www.fanbasis.com/enterprises",
          ]),
    _app(51, "DataForSEO", "data", "https://dataforseo.com", "docs.dataforseo.com",
          ["DataForSEO API authentication documentation"],
          [
              "https://docs.dataforseo.com/v3/auth/",
              "https://docs.dataforseo.com/v3/",
          ]),
    _app(52, "SE Ranking", "data", "https://seranking.com", "seranking.com/api",
          ["SE Ranking API authentication API key documentation"],
          [
              "https://seranking.com/api/data/quickstarts/",
              "https://seranking.com/api/",
              "https://seranking.com/api/se-visible/reference/",
          ]),
    _app(53, "Ahrefs", "data", "https://ahrefs.com", "ahrefs.com/api",
          ["Ahrefs API v3 authentication enterprise documentation"],
          [
              "https://docs.ahrefs.com/docs/api/reference/introduction",
              "https://ahrefs.com/api",
              "https://docs.ahrefs.com/docs/api/reference/authentication",
          ]),
    _app(54, "MrScraper", "data", "https://mrscraper.com", "docs.mrscraper.com",
          ["MrScraper API authentication token documentation"],
          [
              "https://docs.mrscraper.com/docs/api/authentication",
              "https://docs.mrscraper.com/docs/integrations/clawhub",
              "https://docs.mrscraper.com/",
          ]),
    _app(55, "Apify", "data", "https://apify.com", "docs.apify.com",
          ["Apify API authentication token MCP documentation"],
          [
              "https://docs.apify.com/api/v2",
              "https://docs.apify.com/api/client/js/docs/2.23/guides/authentication",
              "https://docs.apify.com/platform/integrations/mcp",
          ]),
    _app(56, "Firecrawl", "data", "https://www.firecrawl.dev", "firecrawl.dev",
          ["Firecrawl API authentication MCP documentation"],
          [
              "https://docs.firecrawl.dev/introduction",
              "https://docs.firecrawl.dev/api-reference/introduction",
              "https://docs.firecrawl.dev/mcp-server",
          ]),
    _app(57, "Bright Data", "data", "https://brightdata.com", "brightdata.com",
          ["Bright Data API authentication documentation"],
          [
              "https://docs.brightdata.com/api-reference/authentication",
              "https://docs.brightdata.com/api-reference/introduction",
              "https://brightdata.com/products/api",
          ]),
    _app(58, "Sherlock", "data", "https://github.com/sherlock-project/sherlock", "github.com/sherlock-project/sherlock",
          ["Sherlock project username search CLI API documentation"],
          [
              "https://github.com/sherlock-project/sherlock",
              "https://raw.githubusercontent.com/sherlock-project/sherlock/master/README.md",
          ]),
    _app(59, "Waterfall.io", "data", "https://waterfall.io", "waterfall.io",
          ["Waterfall.io API authentication documentation"],
          [
              "https://docs.waterfall.io/v1/introduction",
              "https://docs.waterfall.io/",
              "https://waterfall.io/",
          ]),
    _app(60, "Clay", "data", "https://www.clay.com", "clay.com",
          ["Clay public API authentication MCP documentation"],
          [
              "https://developers.clay.com/quickstart",
              "https://developers.clay.com/",
              "https://www.clay.com/mcp",
          ]),
    _app(61, "GitHub", "dev", "https://github.com", "docs.github.com/rest",
          ["GitHub REST API authentication MCP documentation"],
          [
              "https://docs.github.com/en/rest/authentication/authenticating-to-the-rest-api",
              "https://docs.github.com/en/rest",
              "https://github.com/github/github-mcp-server",
          ]),
    _app(62, "Vercel", "dev", "https://vercel.com", "vercel.com/docs/rest-api",
          ["Vercel REST API authentication documentation"],
          [
              "https://vercel.com/docs/rest-api",
              "https://vercel.com/docs/rest-api#authentication",
              "https://vercel.com/docs/mcp",
          ]),
    _app(63, "Netlify", "dev", "https://www.netlify.com", "docs.netlify.com/api",
          ["Netlify API authentication documentation"],
          [
              "https://docs.netlify.com/api/get-started/",
              "https://docs.netlify.com/api-and-cli-guides/api-guides/get-started-with-api/",
          ]),
    _app(64, "Cloudflare", "dev", "https://www.cloudflare.com", "developers.cloudflare.com/api",
          ["Cloudflare API token authentication MCP documentation"],
          [
              "https://developers.cloudflare.com/fundamentals/api/get-started/create-token/",
              "https://developers.cloudflare.com/api/",
              "https://developers.cloudflare.com/agents/model-context-protocol/",
          ]),
    _app(65, "Supabase", "dev", "https://supabase.com", "supabase.com/docs",
          ["Supabase API authentication management API documentation"],
          [
              "https://supabase.com/docs/guides/api",
              "https://supabase.com/docs/reference/api/introduction",
              "https://supabase.com/docs/guides/getting-started/mcp",
          ]),
    _app(66, "Neo4j", "dev", "https://neo4j.com", "neo4j.com/docs/api",
          ["Neo4j HTTP API Aura API authentication documentation"],
          [
              "https://neo4j.com/docs/http-api/current/authentication/",
              "https://neo4j.com/docs/aura/platform/api/authentication/",
              "https://neo4j.com/docs/api/",
          ]),
    _app(67, "Snowflake", "dev", "https://www.snowflake.com", "docs.snowflake.com",
          ["Snowflake SQL API authentication documentation"],
          [
              "https://docs.snowflake.com/en/developer-guide/sql-api/authenticating",
              "https://docs.snowflake.com/en/developer-guide/sql-api/about-sql-api",
              "https://docs.snowflake.com/en/developer-guide/sql-api/intro",
          ]),
    _app(68, "MongoDB Atlas", "dev", "https://www.mongodb.com/atlas", "mongodb.com/docs/atlas/api",
          ["MongoDB Atlas Administration API authentication documentation"],
          [
              "https://www.mongodb.com/docs/atlas/configure-api-access/",
              "https://www.mongodb.com/docs/atlas/api/atlas-admin-api-ref/",
              "https://www.mongodb.com/docs/atlas/api/",
          ]),
    _app(69, "Datadog", "dev", "https://www.datadoghq.com", "docs.datadoghq.com/api",
          ["Datadog API authentication documentation"],
          [
              "https://docs.datadoghq.com/api/latest/authentication/",
              "https://docs.datadoghq.com/api/latest/",
          ]),
    _app(70, "Sentry", "dev", "https://sentry.io", "docs.sentry.io/api",
          ["Sentry API authentication MCP documentation"],
          [
              "https://docs.sentry.io/api/auth/",
              "https://docs.sentry.io/api/",
              "https://docs.sentry.io/product/sentry-mcp/",
          ]),
    _app(71, "Notion", "productivity", "https://www.notion.com", "developers.notion.com",
          ["Notion API authorization MCP documentation"],
          [
              "https://developers.notion.com/docs/authorization",
              "https://developers.notion.com/reference/intro",
              "https://developers.notion.com/docs/mcp",
          ]),
    _app(72, "Airtable", "productivity", "https://www.airtable.com", "airtable.com/developers",
          ["Airtable API authentication documentation"],
          [
              "https://airtable.com/developers/web/api/authentication",
              "https://airtable.com/developers/web/api/introduction",
          ]),
    _app(73, "Linear", "productivity", "https://linear.app", "developers.linear.app",
          ["Linear GraphQL API authentication MCP documentation"],
          [
              "https://developers.linear.app/docs/graphql/working-with-the-graphql-api",
              "https://linear.app/docs/mcp",
              "https://developers.linear.app/docs/oauth/authentication",
          ]),
    _app(74, "Jira", "productivity", "https://www.atlassian.com/software/jira", "developer.atlassian.com",
          ["Jira Cloud REST API OAuth authentication MCP documentation"],
          [
              "https://developer.atlassian.com/cloud/jira/platform/oauth-2-3lo-apps/",
              "https://developer.atlassian.com/cloud/jira/platform/basic-auth-for-rest-apis/",
              "https://developer.atlassian.com/cloud/jira/platform/rest/v3/intro/",
          ]),
    _app(75, "Asana", "productivity", "https://asana.com", "developers.asana.com",
          ["Asana API authentication documentation"],
          [
              "https://developers.asana.com/docs/authentication",
              "https://developers.asana.com/docs/personal-access-token",
          ]),
    _app(76, "Monday.com", "productivity", "https://monday.com", "developer.monday.com",
          ["monday.com API authentication GraphQL documentation"],
          [
              "https://developer.monday.com/api-reference/docs/authentication",
              "https://developer.monday.com/api-reference/docs",
          ]),
    _app(77, "ClickUp", "productivity", "https://clickup.com", "clickup.com/api",
          ["ClickUp API authentication documentation"],
          [
              "https://developer.clickup.com/docs/authentication",
              "https://clickup.com/api",
          ]),
    _app(78, "Coda", "productivity", "https://coda.io", "coda.io/developers",
          ["Coda API authentication documentation"],
          [
              "https://coda.io/developers/apis/v1",
              "https://coda.io/developers/apis/v1#tag/Authentication",
          ]),
    _app(79, "Smartsheet", "productivity", "https://www.smartsheet.com", "smartsheet.com/developers",
          ["Smartsheet API authentication documentation"],
          [
              "https://developers.smartsheet.com/docs/authentication",
              "https://smartsheet.redoc.ly/",
          ]),
    _app(80, "Harvest", "productivity", "https://www.getharvest.com", "help.getharvest.com/api-v2",
          ["Harvest API v2 authentication documentation"],
          [
              "https://help.getharvest.com/api-v2/authentication-api/authentication/authentication/",
              "https://help.getharvest.com/api-v2/",
          ]),
    _app(81, "Stripe", "finance", "https://stripe.com", "stripe.com/docs/api",
          ["Stripe API authentication MCP documentation"],
          [
              "https://docs.stripe.com/api/authentication",
              "https://docs.stripe.com/api",
              "https://docs.stripe.com/mcp",
          ]),
    _app(82, "Plaid", "finance", "https://plaid.com", "plaid.com/docs",
          ["Plaid API authentication sandbox production access documentation"],
          [
              "https://plaid.com/docs/api/",
              "https://plaid.com/docs/quickstart/",
              "https://plaid.com/docs/account/activity/",
          ]),
    _app(83, "Binance", "finance", "https://www.binance.com", "binance-docs.github.io",
          ["Binance spot REST API signed request authentication documentation"],
          [
              "https://developers.binance.com/docs/binance-spot-api-docs/rest-api",
              "https://developers.binance.com/docs/binance-spot-api-docs/rest-api/request-security",
              "https://binance-docs.github.io/apidocs/spot/en/",
          ]),
    _app(84, "Paygent Connect", "finance", "https://www.paygent.co.jp", "paygent (NMI-powered)",
          ["Paygent Connect API NMI authentication documentation", "Paygent payment API merchant authentication"],
          [
              "https://www.paygent.co.jp/en/",
              "https://dev.nmi.com/",
              "https://docs.nmi.com/reference/authentication",
              "https://www.paygent.co.jp/",
          ]),
    _app(85, "iPayX", "finance", "https://ipayx.ai", "ipayx.ai/docs",
          ["iPayX API documentation authentication ipayx.ai"],
          [
              "https://ipayx.ai/docs",
              "https://ipayx.ai/",
              "https://docs.ipayx.ai/",
              "https://mcp.ipayx.ai/mcp",
          ]),
    _app(86, "QuickBooks", "finance", "https://quickbooks.intuit.com", "developer.intuit.com",
          ["QuickBooks Online API OAuth 2.0 documentation"],
          [
              "https://developer.intuit.com/app/developer/qbo/docs/develop/authentication-and-authorization/oauth-2.0",
              "https://developer.intuit.com/app/developer/qbo/docs/get-started",
          ]),
    _app(87, "Xero", "finance", "https://www.xero.com", "developer.xero.com",
          ["Xero API OAuth 2.0 documentation"],
          [
              "https://developer.xero.com/documentation/guides/oauth2/overview/",
              "https://developer.xero.com/documentation/guides/oauth2/auth-flow/",
          ]),
    _app(88, "Brex", "finance", "https://www.brex.com", "developer.brex.com",
          ["Brex API authentication documentation"],
          [
              "https://developer.brex.com/docs/authentication/",
              "https://developer.brex.com/",
              "https://developer.brex.com/openapi/payments_api/",
          ]),
    _app(89, "Ramp", "finance", "https://ramp.com", "docs.ramp.com",
          ["Ramp developer API authorization documentation"],
          [
              "https://docs.ramp.com/developer-api/v1/authorization",
              "https://docs.ramp.com/developer-api/v1/overview",
              "https://docs.ramp.com/",
          ]),
    _app(90, "PitchBook", "finance", "https://pitchbook.com", "pitchbook.com",
          ["PitchBook API access authentication documentation direct data"],
          [
              "https://pitchbook.com/products/direct-data",
              "https://pitchbook.com/",
              "https://pitchbook.com/data",
          ]),
    _app(91, "NotebookLM", "ai", "https://notebooklm.google.com", "cloud.google.com/gemini",
          ["NotebookLM Enterprise API authentication Google Cloud documentation"],
          [
              "https://docs.cloud.google.com/gemini/enterprise/notebooklm-enterprise/docs/api-notebooks",
              "https://cloud.google.com/gemini/enterprise/notebooklm-enterprise/docs/overview",
              "https://docs.cloud.google.com/gemini/enterprise/notebooklm-enterprise/docs/set-up-notebooklm",
          ]),
    _app(92, "Otter AI", "ai", "https://otter.ai", "help.otter.ai",
          ["Otter.ai official MCP server API authentication documentation"],
          [
              "https://help.otter.ai/hc/en-us/articles/35287607569687-Otter-MCP-Server",
              "https://otter.ai/",
              "https://help.otter.ai/hc/en-us/articles/360048318334-Otter-API",
          ]),
    _app(93, "Fathom", "ai", "https://fathom.video", "fathom.video",
          ["Fathom video REST API authentication documentation"],
          [
              "https://developers.fathom.ai/api-overview",
              "https://developers.fathom.ai/",
              "https://developers.fathom.ai/sdks/overview",
          ]),
    _app(94, "Consensus", "ai", "https://consensus.app", "consensus.app",
          ["Consensus.app API OAuth MCP documentation"],
          [
              "https://docs.consensus.app/enterprise/connection-reference",
              "https://docs.consensus.app/",
              "https://consensus.app/",
          ]),
    _app(95, "Reducto", "ai", "https://reducto.ai", "reducto.ai",
          ["Reducto API authentication documentation"],
          [
              "https://docs.reducto.ai/agent-guide",
              "https://docs.reducto.ai/",
              "https://docs.reducto.ai/quickstart",
          ]),
    _app(96, "Devin", "ai", "https://devin.ai", "docs.devin.ai",
          ["Devin API authentication sessions documentation MCP"],
          [
              "https://docs.devin.ai/api-reference/authentication",
              "https://docs.devin.ai/api-reference/overview",
              "https://docs.devin.ai/cli/extensibility/mcp/overview",
          ]),
    _app(97, "higgsfield", "ai", "https://higgsfield.ai", "higgsfield.ai/cli",
          ["Higgsfield API CLI MCP authentication documentation"],
          [
              "https://docs.higgsfield.ai/docs/help/faq",
              "https://higgsfield.ai/cli",
              "https://docs.higgsfield.ai/",
          ]),
    _app(98, "Mermaid CLI", "ai", "https://github.com/mermaid-js/mermaid-cli", "github.com/mermaid-js/mermaid-cli",
          ["mermaid-cli documentation authentication API"],
          [
              "https://github.com/mermaid-js/mermaid-cli",
              "https://raw.githubusercontent.com/mermaid-js/mermaid-cli/master/README.md",
          ]),
    _app(99, "YouTube Transcript", "ai", "https://transcriptapi.com", "transcriptapi.com",
          ["TranscriptAPI YouTube transcript API authentication documentation"],
          [
              "https://transcriptapi.com/docs/api/",
              "https://transcriptapi.com/",
              "https://transcriptapi.com/docs/",
          ]),
    _app(100, "Grain", "ai", "https://grain.com", "grain.com",
           ["Grain meeting notes public API OAuth authentication documentation"],
           [
               "https://developers.grain.com/",
               "https://grain.com/",
               "https://developers.grain.com/docs/authentication",
           ]),
]


def category_name(category_id: str) -> str:
    for cat in CATEGORIES:
        if cat["id"] == category_id:
            return cat["name"]
    return category_id
