"""Adjudicated findings. Every row is from a page the retrieval pass actually returned.

confidence:
  fetched     — an official page returned the claim
  partial     — the official page loaded, but the field was not in the returned text
  unverified  — no usable official page in this pass

Do not treat training-data knowledge as a fill-in. If a field was not on the
page, it stays "Not found" or "Could not verify".
"""

from __future__ import annotations

# Keys are catalog ids. Missing ids are a build error.
FINDINGS: dict[int, dict] = {
    1: {
        "one_liner": "Enterprise CRM for accounts, pipeline, and customer records.",
        "auth_method": "OAuth2",
        "access_type": "Gated",
        "api_surface": "REST",
        "mcp": "None found on the fetched page",
        "buildability_verdict": "Conditional",
        "blocker": "OAuth via an external client app or connected app. As of Spring '26, new connected apps can only be created through the API. A Salesforce org is required; a free developer-edition path was not on this page.",
        "evidence_url": "https://developer.salesforce.com/docs/atlas.en-us.api_rest.meta/api_rest/intro_oauth_and_connected_apps.html",
        "quote": "",
        "confidence": "fetched",
    },
    2: {
        "one_liner": "CRM and marketing platform with a public developer platform.",
        "auth_method": "OAuth2 or API key",
        "access_type": "Self-serve",
        "api_surface": "REST",
        "mcp": "None found on the fetched page",
        "buildability_verdict": "Yes",
        "blocker": "None for a first integration. OAuth for multi-account apps, or a static auth token for a single account. Developer API keys (hapikey) cover some app endpoints only.",
        "evidence_url": "https://developers.hubspot.com/docs/apps/developer-platform/build-apps/authentication/overview",
        "quote": "OAuth is required for multiple accounts, while static auth access tokens are used for installing in a single account at a time.",
        "confidence": "fetched",
    },
    3: {
        "one_liner": "Sales CRM with a public REST API.",
        "auth_method": "OAuth2 or API key",
        "access_type": "Self-serve",
        "api_surface": "REST",
        "mcp": "None found on the fetched page",
        "buildability_verdict": "Yes",
        "blocker": "None. OAuth 2.0 for apps, or a per-user API token sent as x-api-token.",
        "evidence_url": "https://pipedrive.readme.io/docs/core-api-concepts-authentication",
        "quote": "",
        "confidence": "fetched",
    },
    4: {
        "one_liner": "Modern CRM with a public REST API.",
        "auth_method": "OAuth2 or API key",
        "access_type": "Self-serve",
        "api_surface": "REST",
        "mcp": "None found on the fetched page",
        "buildability_verdict": "Yes",
        "blocker": "None. OAuth 2.0 or a workspace API key. Bearer is the documented header; Basic with the token as the username is also supported.",
        "evidence_url": "https://docs.attio.com/rest-api/guides/authentication",
        "quote": "",
        "confidence": "fetched",
    },
    5: {
        "one_liner": "Open-source CRM with per-workspace REST and GraphQL APIs.",
        "auth_method": "OAuth2 or API key",
        "access_type": "Self-serve",
        "api_surface": "REST + GraphQL",
        "mcp": "None found on the fetched page",
        "buildability_verdict": "Yes",
        "blocker": "None. Bearer API key from Settings, API and Webhooks. OAuth is documented for external apps. Cloud base is https://api.twenty.com/.",
        "evidence_url": "https://docs.twenty.com/developers/extend/api",
        "quote": "",
        "confidence": "fetched",
    },
    6: {
        "one_liner": "Work and CRM platform with a public API.",
        "auth_method": "OAuth2",
        "access_type": "Self-serve",
        "api_surface": "REST",
        "mcp": "None found on the fetched page",
        "buildability_verdict": "Yes",
        "blocker": "None. Register an app for a client id and secret. Requests use Authorization: OAuth2 ACCESS_TOKEN.",
        "evidence_url": "https://developers.podio.com/authentication",
        "quote": "",
        "confidence": "fetched",
    },
    7: {
        "one_liner": "Zoho's CRM, with a public developer guide.",
        "auth_method": "OAuth2",
        "access_type": "Could not verify",
        "api_surface": "Could not verify",
        "mcp": "Could not verify",
        "buildability_verdict": "Could not verify",
        "blocker": "The official v8 page is titled OAuth 2.0 overview, but the retrieved chunk was navigation, not the auth body. Self-serve signup was not in the retrieved text.",
        "evidence_url": "https://www.zoho.com/crm/developer/docs/api/v8/oauth-overview.html",
        "quote": "",
        "confidence": "partial",
    },
    8: {
        "one_liner": "Sales CRM with a public API and a hosted MCP server.",
        "auth_method": "API key (HTTP Basic) or OAuth2",
        "access_type": "Self-serve",
        "api_surface": "REST + MCP",
        "mcp": "Official action server at https://mcp.close.com/mcp",
        "buildability_verdict": "Yes",
        "blocker": "None. API key is the Basic username with an empty password, or use OAuth 2.0. Keys are in Settings, Developer.",
        "evidence_url": "https://developer.close.com/api/overview/api-key-authentication",
        "quote": "",
        "confidence": "fetched",
    },
    9: {
        "one_liner": "Google-Workspace-native CRM with a public API.",
        "auth_method": "API key or OAuth2",
        "access_type": "Self-serve",
        "api_surface": "REST",
        "mcp": "None found on the fetched page",
        "buildability_verdict": "Yes",
        "blocker": "None for a first integration. API key (a token header plus the user email) or OAuth 2.0. Exact header names were not in the retrieved chunk.",
        "evidence_url": "https://developer.copper.com/introduction/authentication.html",
        "quote": "",
        "confidence": "fetched",
    },
    10: {
        "one_liner": "Deal and relationship CRM used by finance and advisory firms.",
        "auth_method": "OAuth2 (client credentials)",
        "access_type": "Gated",
        "api_surface": "REST",
        "mcp": "None found on the fetched page",
        "buildability_verdict": "Conditional",
        "blocker": "Token endpoint is client_id plus client_secret, Bearer, site-specific base URL. A public signup was not on the token page. Treat it as an existing-customer API until a signup page is verified.",
        "evidence_url": "https://api.docs.dealcloud.com/docs/token",
        "quote": "",
        "confidence": "fetched",
    },
    11: {
        "one_liner": "Support suite with a public ticketing API.",
        "auth_method": "OAuth2",
        "access_type": "Self-serve",
        "api_surface": "REST",
        "mcp": "None found on the fetched page",
        "buildability_verdict": "Yes",
        "blocker": "API-token Basic auth (email/token:token) is deprecated. New work should use OAuth Bearer. A verified Zendesk user can start; multi-customer apps use global OAuth.",
        "evidence_url": "https://developer.zendesk.com/api-reference/introduction/security-and-auth/",
        "quote": "",
        "confidence": "fetched",
    },
    12: {
        "one_liner": "Customer messaging platform with a public API.",
        "auth_method": "API key or OAuth2",
        "access_type": "Self-serve",
        "api_surface": "REST",
        "mcp": "None found on the fetched page",
        "buildability_verdict": "Yes",
        "blocker": "None. Private-app access token or public-app OAuth, both Bearer. Apps are created in the Developer Hub.",
        "evidence_url": "https://developers.intercom.com/docs/build-an-integration/learn-more/authentication",
        "quote": "",
        "confidence": "fetched",
    },
    13: {
        "one_liner": "Freshworks helpdesk.",
        "auth_method": "Not found",
        "access_type": "Could not verify",
        "api_surface": "Could not verify",
        "mcp": "Could not verify",
        "buildability_verdict": "Could not verify",
        "blocker": "developers.freshdesk.com/api/ loaded a table of contents only. The authentication section body was not in the retrieved chunk. Do not fill this from memory.",
        "evidence_url": "https://developers.freshdesk.com/api/",
        "quote": "",
        "confidence": "partial",
    },
    14: {
        "one_liner": "Shared inbox with a public API and an MCP token scope.",
        "auth_method": "API key or OAuth2",
        "access_type": "Self-serve",
        "api_surface": "REST",
        "mcp": "MCP server is a documented token scope; hosted URL was not on this page",
        "buildability_verdict": "Yes",
        "blocker": "None for REST. Bearer API token, or OAuth for public apps.",
        "evidence_url": "https://dev.frontapp.com/docs/authentication",
        "quote": "",
        "confidence": "fetched",
    },
    15: {
        "one_liner": "B2B support platform with a hosted MCP server.",
        "auth_method": "OAuth2",
        "access_type": "Self-serve",
        "api_surface": "MCP",
        "mcp": "Official hosted MCP, OAuth per user",
        "buildability_verdict": "Yes",
        "blocker": "The fetched page documents MCP, not REST. A REST surface was not verified. Plan requirements were not on the page.",
        "evidence_url": "https://www.usepylon.com/integrations/mcp",
        "quote": "",
        "confidence": "fetched",
    },
    16: {
        "one_liner": "Helpdesk with a v3 REST API.",
        "auth_method": "API key",
        "access_type": "Self-serve",
        "api_surface": "REST",
        "mcp": "None found on the fetched page",
        "buildability_verdict": "Yes",
        "blocker": "An account admin generates the key. Send it in the apikey header. Base is https://your.ladesk.com/api/v3/.",
        "evidence_url": "https://support.liveagent.com/741982-API-key",
        "quote": "",
        "confidence": "fetched",
    },
    17: {
        "one_liner": "Support platform whose public API is GraphQL.",
        "auth_method": "API key",
        "access_type": "Self-serve",
        "api_surface": "GraphQL",
        "mcp": "None found on the fetched page",
        "buildability_verdict": "Yes",
        "blocker": "None. Machine-user API key as a Bearer token.",
        "evidence_url": "https://www.plain.com/docs/graphql/authentication",
        "quote": "",
        "confidence": "fetched",
    },
    18: {
        "one_liner": "Shared inbox with a mailbox API.",
        "auth_method": "OAuth2",
        "access_type": "Self-serve",
        "api_surface": "REST",
        "mcp": "None found on the fetched page",
        "buildability_verdict": "Yes",
        "blocker": "None. Authorization-code or client-credentials OAuth, Bearer. Create the app under Profile, My apps.",
        "evidence_url": "https://developer.helpscout.com/mailbox-api/overview/authentication/",
        "quote": "",
        "confidence": "fetched",
    },
    19: {
        "one_liner": "Ecommerce helpdesk with a public API.",
        "auth_method": "API key or OAuth2",
        "access_type": "Self-serve",
        "api_surface": "REST",
        "mcp": "None found on the fetched page",
        "buildability_verdict": "Yes",
        "blocker": "None. Private-app API key (email as username) or OAuth2 for public apps.",
        "evidence_url": "https://developers.gorgias.com/reference/authentication",
        "quote": "",
        "confidence": "fetched",
    },
    20: {
        "one_liner": "Enterprise customer-service platform.",
        "auth_method": "API key",
        "access_type": "Gated",
        "api_surface": "REST",
        "mcp": "Could not verify",
        "buildability_verdict": "Conditional",
        "blocker": "REST is at {org}.gladly.com. An API User permission and an API token are required. The authentication section was cut off, so the header scheme was not verified. This is an existing-org credential, not a public sandbox.",
        "evidence_url": "https://developer.gladly.com/rest/",
        "quote": "",
        "confidence": "partial",
    },
    21: {
        "one_liner": "Team messaging with a Web API and a hosted MCP server.",
        "auth_method": "OAuth2",
        "access_type": "Self-serve",
        "api_surface": "REST + MCP",
        "mcp": "Official action server at https://mcp.slack.com/mcp",
        "buildability_verdict": "Yes",
        "blocker": "App creation is self-serve. Public distribution needs Slack app review. The MCP server does not support dynamic client registration. Workspace admins approve MCP clients.",
        "evidence_url": "https://docs.slack.dev/ai/slack-mcp-server/",
        "quote": "All requests should be sent to https://mcp.slack.com/mcp. We do not support SSE-based connections or Dynamic Client Registration at this time.",
        "confidence": "fetched",
    },
    22: {
        "one_liner": "Communications APIs for SMS, voice, and related products.",
        "auth_method": "Basic (API key)",
        "access_type": "Self-serve",
        "api_surface": "REST",
        "mcp": "Official, but docs-only: it does not execute API calls",
        "buildability_verdict": "Yes",
        "blocker": "REST is the buildable surface: HTTP Basic with an API key SID and secret, or Account SID and Auth Token. The hosted MCP at mcp.twilio.com/docs requires no account and only searches public specs.",
        "evidence_url": "https://www.twilio.com/docs/usage/requests-to-twilio",
        "quote": "",
        "confidence": "fetched",
    },
    23: {
        "one_liner": "Zoho team chat with a REST API.",
        "auth_method": "OAuth2",
        "access_type": "Self-serve",
        "api_surface": "REST",
        "mcp": "None found on the fetched page",
        "buildability_verdict": "Yes",
        "blocker": "None. Register the client at accounts.zoho.com/developerconsole. Hosts differ by data center.",
        "evidence_url": "https://www.zoho.com/cliq/help/restapi/v2/",
        "quote": "",
        "confidence": "fetched",
    },
    24: {
        "one_liner": "Lark / Feishu collaboration suite with an open platform.",
        "auth_method": "App secret (tenant token) or OAuth2",
        "access_type": "Self-serve",
        "api_surface": "REST",
        "mcp": "None found on the fetched page",
        "buildability_verdict": "Yes",
        "blocker": "None for a custom app. Exchange app_id and app_secret for a tenant_access_token. User OAuth is also in the docs nav.",
        "evidence_url": "https://open.larksuite.com/document/server-docs/getting-started/api-access-token/auth-v3/tenant_access_token_internal",
        "quote": "",
        "confidence": "fetched",
    },
    25: {
        "one_liner": "Team chat app. Official API reference was not retrieved.",
        "auth_method": "Not found",
        "access_type": "Could not verify",
        "api_surface": "Could not verify",
        "mcp": "Could not verify",
        "buildability_verdict": "Could not verify",
        "blocker": "No first-party developer reference returned content in this pass. Do not use third-party connector descriptions as evidence.",
        "evidence_url": "",
        "quote": "",
        "confidence": "unverified",
    },
    26: {
        "one_liner": "Community chat with a public bot API.",
        "auth_method": "Bot token",
        "access_type": "Self-serve",
        "api_surface": "REST",
        "mcp": "None found on the fetched page",
        "buildability_verdict": "Yes",
        "blocker": "Creating an app and a bot token is self-serve in the developer portal. Privileged intents need Discord verification before wide use.",
        "evidence_url": "https://docs.discord.com/developers/quick-start/getting-started",
        "quote": "",
        "confidence": "fetched",
    },
    27: {
        "one_liner": "Messaging platform. The Bot API page did not load.",
        "auth_method": "Not found",
        "access_type": "Could not verify",
        "api_surface": "Could not verify",
        "mcp": "Could not verify",
        "buildability_verdict": "Could not verify",
        "blocker": "https://core.telegram.org/bots/api returned HTTP 403 to the retrieval tool. Not verified in this pass.",
        "evidence_url": "https://core.telegram.org/bots/api",
        "quote": "",
        "confidence": "unverified",
    },
    28: {
        "one_liner": "WhatsApp Cloud API on the Meta developer platform.",
        "auth_method": "Access token",
        "access_type": "Self-serve to start, gated for production",
        "api_surface": "REST",
        "mcp": "None found on the fetched page",
        "buildability_verdict": "Conditional",
        "blocker": "A Meta developer app and a temporary token are documented. The fetched page was cut off before the permanent system-user token steps, so production business verification was not confirmed here.",
        "evidence_url": "https://developers.facebook.com/documentation/business-messaging/whatsapp/get-started",
        "quote": "",
        "confidence": "partial",
    },
    29: {
        "one_liner": "Cloud phone system with public developer docs.",
        "auth_method": "Not found",
        "access_type": "Could not verify",
        "api_surface": "REST",
        "mcp": "Marked coming soon on the intro page",
        "buildability_verdict": "Could not verify",
        "blocker": "The auth tutorial URL redirected to the introduction. REST and webhooks are documented. The auth scheme was not on that page, so no verdict.",
        "evidence_url": "https://developer.aircall.io/docs/introduction",
        "quote": "",
        "confidence": "partial",
    },
    30: {
        "one_liner": "Communications APIs (SMS, voice, and related products).",
        "auth_method": "API key (Basic) or JWT",
        "access_type": "Self-serve",
        "api_surface": "REST",
        "mcp": "None found on the fetched page",
        "buildability_verdict": "Yes",
        "blocker": "None. API key and secret (Basic) and/or JWT, depending on the product. Credentials come from the dashboard.",
        "evidence_url": "https://developer.vonage.com/en/getting-started/concepts/authentication",
        "quote": "",
        "confidence": "fetched",
    },
    31: {
        "one_liner": "Google search and display advertising API.",
        "auth_method": "Developer token (OAuth page not retrieved)",
        "access_type": "Gated",
        "api_surface": "REST",
        "mcp": "None found on the fetched page",
        "buildability_verdict": "Conditional",
        "blocker": "A developer token and access level are required. Basic and Standard access need an application and brand verification. The OAuth overview itself was not the page that loaded.",
        "evidence_url": "https://developers.google.com/google-ads/api/docs/api-policy/developer-token",
        "quote": "",
        "confidence": "partial",
    },
    32: {
        "one_liner": "Meta advertising API for Facebook, Instagram, and related placements.",
        "auth_method": "Not found",
        "access_type": "Could not verify",
        "api_surface": "REST",
        "mcp": "None found on the fetched page",
        "buildability_verdict": "Could not verify",
        "blocker": "The Marketing API overview confirms a public API for campaigns, ad sets, and ads. Auth and app review were not on that page. Do not copy the WhatsApp token flow across.",
        "evidence_url": "https://developers.facebook.com/documentation/ads-commerce/marketing-api/overview",
        "quote": "Use the Marketing API to automate advertising across Meta technologies.",
        "confidence": "partial",
    },
    33: {
        "one_liner": "LinkedIn advertising API.",
        "auth_method": "OAuth2",
        "access_type": "Self-serve to start, gated for production",
        "api_surface": "REST",
        "mcp": "None found on the fetched page",
        "buildability_verdict": "Conditional",
        "blocker": "OAuth 2.0 with rw_ads. A development tier can start; higher access is an application, not a self-serve toggle.",
        "evidence_url": "https://learn.microsoft.com/en-us/linkedin/marketing/integrations/ads/getting-started",
        "quote": "",
        "confidence": "fetched",
    },
    34: {
        "one_liner": "All-in-one sales and marketing platform (HighLevel).",
        "auth_method": "OAuth2 or private integration token",
        "access_type": "Self-serve",
        "api_surface": "REST",
        "mcp": "None found on the fetched page",
        "buildability_verdict": "Yes",
        "blocker": "Docs show a marketplace app or a private integration, then OAuth 2.0 or a private integration token, sent as Bearer. Plan-tier limits were not on this page.",
        "evidence_url": "https://marketplace.gohighlevel.com/docs/",
        "quote": "Choose Integration Type — Marketplace app or Private integration. Set Up Authentication — OAuth 2.0 or Private Integration Token.",
        "confidence": "fetched",
    },
    35: {
        "one_liner": "Email marketing platform with a Marketing API.",
        "auth_method": "API key (HTTP Basic) or OAuth2",
        "access_type": "Self-serve",
        "api_surface": "REST",
        "mcp": "None found on the fetched page",
        "buildability_verdict": "Yes",
        "blocker": "None. Create an account, generate a key, call the API as HTTP Basic anystring:apikey. OAuth 2 is the path for other people's accounts.",
        "evidence_url": "https://mailchimp.com/developer/marketing/guides/quick-start/",
        "quote": "The simplest way to authenticate a request to the Marketing API is using an API key.",
        "confidence": "fetched",
    },
    36: {
        "one_liner": "Messaging and flows platform with a public API.",
        "auth_method": "API key or OAuth2",
        "access_type": "Self-serve",
        "api_surface": "REST",
        "mcp": "None found on the fetched page",
        "buildability_verdict": "Yes",
        "blocker": "None. Private key in Authorization: Klaviyo-API-Key, or OAuth for partners. Keys require Owner, Admin, or Manager.",
        "evidence_url": "https://developers.klaviyo.com/en/docs/authenticate_",
        "quote": "",
        "confidence": "fetched",
    },
    37: {
        "one_liner": "Funnel and email tool with a public API.",
        "auth_method": "API key",
        "access_type": "Self-serve",
        "api_surface": "REST",
        "mcp": "None found on the fetched page",
        "buildability_verdict": "Yes",
        "blocker": "None. Send X-API-Key from the profile Public API keys page.",
        "evidence_url": "https://developer.systeme.io/reference/api",
        "quote": "",
        "confidence": "fetched",
    },
    38: {
        "one_liner": "Pinterest developer platform, including ads.",
        "auth_method": "OAuth2",
        "access_type": "Gated",
        "api_surface": "REST",
        "mcp": "None found on the fetched page",
        "buildability_verdict": "Conditional",
        "blocker": "Trial access waits on app review. Sandbox comes after approval, not before.",
        "evidence_url": "https://developers.pinterest.com/docs/getting-started/connect-app/",
        "quote": "",
        "confidence": "fetched",
    },
    39: {
        "one_liner": "Threads publishing and reading API on the Meta platform.",
        "auth_method": "OAuth2",
        "access_type": "Self-serve to start, gated for production",
        "api_surface": "REST",
        "mcp": "None found on the fetched page",
        "buildability_verdict": "Conditional",
        "blocker": "Threads testers can grant permissions immediately. Users without an app role require App Review, and the app must be published.",
        "evidence_url": "https://developers.facebook.com/documentation/threads/get-started",
        "quote": "Threads testers can grant your app these permissions at any time. In order for app users without a role on your app to be able to grant your app these permissions, each permission must first be approved through the App Review process.",
        "confidence": "fetched",
    },
    40: {
        "one_liner": "Transactional email API, now under Twilio.",
        "auth_method": "API key",
        "access_type": "Self-serve",
        "api_surface": "REST",
        "mcp": "Indexed by the Twilio docs MCP; that server does not send email",
        "buildability_verdict": "Yes",
        "blocker": "None. Authorization: Bearer with a key from the SendGrid account settings.",
        "evidence_url": "https://www.twilio.com/docs/sendgrid/api-reference/how-to-use-the-sendgrid-v3-api/authentication",
        "quote": "To use an API key, include an Authorization header with the value Bearer <YOUR_API_KEY_HERE> in your request.",
        "confidence": "fetched",
    },
    41: {
        "one_liner": "Hosted commerce platform. Current admin surface on the fetched page is GraphQL.",
        "auth_method": "OAuth2",
        "access_type": "Self-serve",
        "api_surface": "GraphQL",
        "mcp": "None found on the fetched page",
        "buildability_verdict": "Yes",
        "blocker": "Dev stores and the CLI are self-serve. Token exchange, auth code, or client credentials; send X-Shopify-Access-Token. This page does not document REST Admin as a current surface. App Store listing is a separate review.",
        "evidence_url": "https://shopify.dev/docs/apps/build/authentication-authorization",
        "quote": "",
        "confidence": "fetched",
    },
    42: {
        "one_liner": "WordPress commerce plugin with a REST API.",
        "auth_method": "API key (HTTP Basic)",
        "access_type": "Self-serve",
        "api_surface": "REST",
        "mcp": "None found on the fetched page",
        "buildability_verdict": "Yes",
        "blocker": "You need a WordPress site with WooCommerce. Consumer key and secret use Basic auth. Keys are created under WooCommerce, Settings, Advanced, REST API.",
        "evidence_url": "https://developer.woocommerce.com/docs/apis/rest-api/",
        "quote": "",
        "confidence": "fetched",
    },
    43: {
        "one_liner": "Hosted commerce platform with store and app APIs.",
        "auth_method": "OAuth2",
        "access_type": "Self-serve",
        "api_surface": "REST + GraphQL",
        "mcp": "None found on the fetched page",
        "buildability_verdict": "Yes",
        "blocker": "None for a store you control. Create API-account credentials in the control panel. Static store access tokens and OAuth app credentials are both documented.",
        "evidence_url": "https://docs.bigcommerce.com/developer/docs/overview/api-fundamentals/api-accounts",
        "quote": "",
        "confidence": "fetched",
    },
    44: {
        "one_liner": "Salesforce B2C Commerce (SFCC) APIs.",
        "auth_method": "OAuth2",
        "access_type": "Gated",
        "api_surface": "REST",
        "mcp": "None found on the fetched page",
        "buildability_verdict": "Conditional",
        "blocker": "SCAPI uses OAuth 2.1 scopes. Shopper APIs go through SLAS; Admin APIs need an Account Manager API client. A B2C Commerce instance is required.",
        "evidence_url": "https://developer.salesforce.com/docs/commerce/commerce-api/guide/authorization.html",
        "quote": "",
        "confidence": "fetched",
    },
    45: {
        "one_liner": "Adobe Commerce (Magento) web APIs.",
        "auth_method": "Token or OAuth2",
        "access_type": "Gated",
        "api_surface": "REST",
        "mcp": "None found on the fetched page",
        "buildability_verdict": "Conditional",
        "blocker": "Admin token, integration token, or third-party OAuth. You need a Commerce instance. Open Source can be self-hosted; Adobe's hosted product is not a free signup. PaaS and SaaS IMS differ.",
        "evidence_url": "https://developer.adobe.com/commerce/webapi/get-started/authentication/",
        "quote": "",
        "confidence": "fetched",
    },
    46: {
        "one_liner": "Website builder with Commerce APIs.",
        "auth_method": "API key or OAuth2",
        "access_type": "Gated",
        "api_surface": "REST",
        "mcp": "None found on the fetched page",
        "buildability_verdict": "Conditional",
        "blocker": "A custom API key requires the Commerce Advanced plan. Extension developers register an OAuth client separately. The old authentication URL 404s; use authentication-and-permissions.",
        "evidence_url": "https://developers.squarespace.com/commerce-apis/authentication-and-permissions",
        "quote": "With Squarespace's Commerce Advanced plan, you can develop a custom application for a Squarespace merchant site.",
        "confidence": "fetched",
    },
    47: {
        "one_liner": "Lightspeed/Ecwid store platform with a developer hub.",
        "auth_method": "Not found",
        "access_type": "Could not verify",
        "api_surface": "Could not verify",
        "mcp": "Could not verify",
        "buildability_verdict": "Could not verify",
        "blocker": "docs.ecwid.com loaded a developer hub (apps, webhooks, orders). The authentication URL 404'd, so the scheme was not verified.",
        "evidence_url": "https://docs.ecwid.com/",
        "quote": "",
        "confidence": "partial",
    },
    48: {
        "one_liner": "Creator commerce with an OAuth REST API and a CLI.",
        "auth_method": "OAuth2",
        "access_type": "Self-serve",
        "api_surface": "REST",
        "mcp": "CLI for agents; hosted MCP not on this page",
        "buildability_verdict": "Yes",
        "blocker": "None. Register an OAuth application in settings and generate an access token. License verification is the one endpoint that does not need an OAuth app.",
        "evidence_url": "https://gumroad.com/api",
        "quote": "The Gumroad OAuth API is based around REST. To start using the API, you'll need to register your OAuth application.",
        "confidence": "fetched",
    },
    49: {
        "one_liner": "Amazon seller API (Selling Partner API).",
        "auth_method": "OAuth2 (Login with Amazon)",
        "access_type": "Gated",
        "api_surface": "REST",
        "mcp": "None found on the fetched page",
        "buildability_verdict": "Conditional",
        "blocker": "LWA refresh_token or client_credentials, sent as x-amz-access-token. The app must be registered and authorized by a selling partner. SigV4 was not in the fetched chunk.",
        "evidence_url": "https://developer-docs.amazon.com/sp-api/docs/connecting-to-the-selling-partner-api",
        "quote": "",
        "confidence": "fetched",
    },
    50: {
        "one_liner": "Creator monetization product. No official API reference was found.",
        "auth_method": "Not found",
        "access_type": "Could not verify",
        "api_surface": "Could not verify",
        "mcp": "Could not verify",
        "buildability_verdict": "Could not verify",
        "blocker": "No official developer-docs URL returned content. Marketing pages are not evidence of an API. Do not build against a guessed host.",
        "evidence_url": "",
        "quote": "",
        "confidence": "unverified",
    },
    51: {
        "one_liner": "SEO data API with a public signup.",
        "auth_method": "Basic (API login and password)",
        "access_type": "Self-serve",
        "api_surface": "REST",
        "mcp": "None found on the fetched page",
        "buildability_verdict": "Yes",
        "blocker": "None. Basic auth with the login and password from the API Access tab. Free account registration is documented.",
        "evidence_url": "https://docs.dataforseo.com/v3/auth/",
        "quote": "",
        "confidence": "fetched",
    },
    52: {
        "one_liner": "SEO data API billed in credits.",
        "auth_method": "API key",
        "access_type": "Could not verify",
        "api_surface": "REST",
        "mcp": "None found on the fetched page",
        "buildability_verdict": "Conditional",
        "blocker": "An active account and an API key are required. The header format is not on the quickstart page. Credits and usage tiers are documented; a free tier was not.",
        "evidence_url": "https://seranking.com/api/data/quickstarts/",
        "quote": "Before making requests, make sure you have an active SE Ranking account and an API key generated from your account.",
        "confidence": "partial",
    },
    53: {
        "one_liner": "SEO data API. Useful queries sit on eligible paid plans.",
        "auth_method": "API key",
        "access_type": "Gated",
        "api_surface": "REST",
        "mcp": "None found on the fetched page",
        "buildability_verdict": "Conditional",
        "blocker": "Not an enterprise-only black box. Eligible paid plans include API units; other plans get a limited set of free test queries. Only workspace owners and admins can create keys. Header format was not on the introduction page.",
        "evidence_url": "https://docs.ahrefs.com/en/api/docs/introduction",
        "quote": "Ahrefs API is available on eligible paid plans. On all other plans, you'll still have access to a limited set of free test queries.",
        "confidence": "fetched",
    },
    54: {
        "one_liner": "Scraping API with dashboard-issued tokens.",
        "auth_method": "API key",
        "access_type": "Self-serve",
        "api_surface": "REST",
        "mcp": "None found on the fetched page",
        "buildability_verdict": "Yes",
        "blocker": "None to start. Send x-api-token. Marketplace endpoints use Authorization: Bearer with the same token. Usage draws on the account plan.",
        "evidence_url": "https://docs.mrscraper.com/docs/api/authentication",
        "quote": "Include your API token in the x-api-token HTTP header on every request.",
        "confidence": "fetched",
    },
    55: {
        "one_liner": "Actor platform for web scraping and automation.",
        "auth_method": "API key",
        "access_type": "Self-serve",
        "api_surface": "REST",
        "mcp": "None found on the fetched page",
        "buildability_verdict": "Yes",
        "blocker": "None. Bearer token from the Apify Console integrations page. Agents can also pay per run via x402 without an account; that path was documented, not tested.",
        "evidence_url": "https://docs.apify.com/api/v2",
        "quote": "Add the token to your request's Authorization header as Bearer <token>.",
        "confidence": "fetched",
    },
    56: {
        "one_liner": "Web scrape, crawl, and search API, plus a hosted MCP server.",
        "auth_method": "API key or OAuth2",
        "access_type": "Self-serve",
        "api_surface": "REST + MCP",
        "mcp": "Official action server at https://mcp.firecrawl.dev",
        "buildability_verdict": "Yes",
        "blocker": "None. REST uses Authorization: Bearer. MCP can be keyless within daily limits, OAuth, or an API key.",
        "evidence_url": "https://docs.firecrawl.dev/api-reference/introduction",
        "quote": "For authentication, it's required to include an Authorization header. The header should contain Bearer fc-123456789, where fc-123456789 represents your API Key.",
        "confidence": "fetched",
    },
    57: {
        "one_liner": "Proxy and web-data platform with an API and an MCP key type.",
        "auth_method": "API key or proxy username/password",
        "access_type": "Self-serve",
        "api_surface": "REST + MCP",
        "mcp": "Agent API keys are documented for the Bright Data MCP server",
        "buildability_verdict": "Yes",
        "blocker": "A default API key is created with the account. Extra keys are an admin action. Send Authorization: Bearer. Proxy zones also accept username and password.",
        "evidence_url": "https://docs.brightdata.com/api-reference/authentication",
        "quote": "Agent API keys authenticate the Bright Data MCP server and AI agents.",
        "confidence": "fetched",
    },
    58: {
        "one_liner": "Username search tool distributed as a GitHub project.",
        "auth_method": "Not found",
        "access_type": "Could not verify",
        "api_surface": "Could not verify",
        "mcp": "Could not verify",
        "buildability_verdict": "Could not verify",
        "blocker": "The official repository returned HTTP 200, but the retrieved text was GitHub navigation chrome, not the README. No hosted API was documented in that text. Do not invent one.",
        "evidence_url": "https://github.com/sherlock-project/sherlock",
        "quote": "",
        "confidence": "partial",
    },
    59: {
        "one_liner": "Contact and company enrichment API.",
        "auth_method": "API key",
        "access_type": "Could not verify",
        "api_surface": "REST",
        "mcp": "Agent skills repo; hosted MCP not on this page",
        "buildability_verdict": "Conditional",
        "blocker": "Public REST at https://api.waterfall.io with x-api-key. How a developer gets the first key was not on the introduction page.",
        "evidence_url": "https://docs.waterfall.io/v1/introduction",
        "quote": "The Waterfall API is available at https://api.waterfall.io. All requests require an API key in the x-api-key header.",
        "confidence": "fetched",
    },
    60: {
        "one_liner": "GTM data platform with a public API (beta keys) and an agent plugin.",
        "auth_method": "API key",
        "access_type": "Self-serve",
        "api_surface": "REST",
        "mcp": "Agent plugin and CLI; hosted MCP not on the quickstart page",
        "buildability_verdict": "Yes",
        "blocker": "Keys are beta, created under Settings, Account, API keys. Send clay-api-key. The plugin path needs a coding agent that can run a CLI, not a chat-only client.",
        "evidence_url": "https://developers.clay.com/quickstart",
        "quote": "Requests authenticate with a Clay API key in the clay-api-key header.",
        "confidence": "fetched",
    },
    61: {
        "one_liner": "Git hosting with a REST API and an official MCP server.",
        "auth_method": "Token (PAT, GitHub App, or OAuth)",
        "access_type": "Self-serve",
        "api_surface": "REST + MCP",
        "mcp": "Official repository confirmed: github/github-mcp-server",
        "buildability_verdict": "Yes",
        "blocker": "None. Fine-grained PAT, GitHub App token, or OAuth token, sent as Bearer. The MCP repo page title confirms it is GitHub's official MCP server; its tool list was not re-read in this pass.",
        "evidence_url": "https://docs.github.com/en/rest/authentication/authenticating-to-the-rest-api",
        "quote": "You can create a personal access token, generate a token with a GitHub App, or use the built-in GITHUB_TOKEN in a GitHub Actions workflow.",
        "confidence": "fetched",
    },
    62: {
        "one_liner": "Frontend hosting platform with a REST API.",
        "auth_method": "API key",
        "access_type": "Self-serve",
        "api_surface": "REST",
        "mcp": "None found on the fetched page",
        "buildability_verdict": "Yes",
        "blocker": "None. Access token from account settings, sent as Authorization: Bearer.",
        "evidence_url": "https://vercel.com/docs/rest-api#authentication",
        "quote": "Vercel Access Tokens are required to authenticate and use the Vercel API. Include the token in the Authorization header: Authorization: Bearer <TOKEN>.",
        "confidence": "fetched",
    },
    63: {
        "one_liner": "Frontend hosting and deploy API.",
        "auth_method": "OAuth2 or personal access token",
        "access_type": "Self-serve",
        "api_surface": "REST",
        "mcp": "None found on the fetched page",
        "buildability_verdict": "Yes",
        "blocker": "None. Create a personal access token under Applications, or register an OAuth app for other users.",
        "evidence_url": "https://docs.netlify.com/api-and-cli-guides/api-guides/get-started-with-api/",
        "quote": "Netlify uses OAuth2 for authentication. To generate a personal access token: go to Applications, Personal access tokens.",
        "confidence": "fetched",
    },
    64: {
        "one_liner": "Edge and DNS platform with a token-scoped REST API.",
        "auth_method": "API key",
        "access_type": "Self-serve",
        "api_surface": "REST",
        "mcp": "Docs describe hosting your own MCP server, not a Cloudflare-account MCP",
        "buildability_verdict": "Yes",
        "blocker": "None for the REST API. Create a token in the dashboard and send Authorization: Bearer. Do not treat the Agents MCP guide as an account connector.",
        "evidence_url": "https://developers.cloudflare.com/fundamentals/api/get-started/create-token/",
        "quote": "curl \"https://api.cloudflare.com/client/v4/user/tokens/verify\" --header \"Authorization: Bearer <API_TOKEN>\"",
        "confidence": "fetched",
    },
    65: {
        "one_liner": "Hosted Postgres with auto-generated project APIs.",
        "auth_method": "API key",
        "access_type": "Self-serve",
        "api_surface": "REST",
        "mcp": "None found on the fetched page",
        "buildability_verdict": "Yes",
        "blocker": "None. Publishable and secret keys are created with the project. anon and service_role keys are deprecated by the end of 2026. Secret keys bypass row-level security.",
        "evidence_url": "https://supabase.com/docs/guides/getting-started/api-keys",
        "quote": "Every request to your Supabase project carries an API key.",
        "confidence": "fetched",
    },
    66: {
        "one_liner": "Graph database. The HTTP auth page did not load.",
        "auth_method": "Not found",
        "access_type": "Could not verify",
        "api_surface": "Could not verify",
        "mcp": "Could not verify",
        "buildability_verdict": "Could not verify",
        "blocker": "https://neo4j.com/docs/http-api/current/authentication/ returned 404. A free console exists on the marketing nav. That is not API evidence.",
        "evidence_url": "https://neo4j.com/docs/http-api/current/authentication/",
        "quote": "",
        "confidence": "unverified",
    },
    67: {
        "one_liner": "Cloud data warehouse with a SQL REST API.",
        "auth_method": "OAuth2, key-pair JWT, or programmatic access token",
        "access_type": "Gated",
        "api_surface": "REST",
        "mcp": "None found on the fetched page",
        "buildability_verdict": "Conditional",
        "blocker": "The SQL API is documented. You need a Snowflake account and a user with a key pair, OAuth token, or programmatic access token. A free trial was not on this page.",
        "evidence_url": "https://docs.snowflake.com/en/developer-guide/sql-api/authenticating",
        "quote": "Using OAuth. Using key-pair authentication. Using workload identity federation.",
        "confidence": "fetched",
    },
    68: {
        "one_liner": "MongoDB Atlas. Official API page was not retrieved.",
        "auth_method": "Not found",
        "access_type": "Could not verify",
        "api_surface": "Could not verify",
        "mcp": "Could not verify",
        "buildability_verdict": "Could not verify",
        "blocker": "No Atlas admin or Data API page was retrieved in this pass. Left unverified on purpose.",
        "evidence_url": "",
        "quote": "",
        "confidence": "unverified",
    },
    69: {
        "one_liner": "Observability platform. The auth page did not return a scheme.",
        "auth_method": "Not found",
        "access_type": "Could not verify",
        "api_surface": "Could not verify",
        "mcp": "Could not verify",
        "buildability_verdict": "Could not verify",
        "blocker": "https://docs.datadoghq.com/api/latest/authentication/ loaded site navigation, not the authentication body. No header scheme is claimed.",
        "evidence_url": "https://docs.datadoghq.com/api/latest/authentication/",
        "quote": "",
        "confidence": "partial",
    },
    70: {
        "one_liner": "Error and tracing platform with a hosted MCP server.",
        "auth_method": "OAuth2",
        "access_type": "Self-serve",
        "api_surface": "MCP",
        "mcp": "Official action server at https://mcp.sentry.dev/mcp",
        "buildability_verdict": "Yes",
        "blocker": "MCP OAuth is self-serve against a Sentry account. The REST API auth page was not retrieved in this pass, so REST is not claimed.",
        "evidence_url": "https://mcp.sentry.dev/",
        "quote": "Sentry MCP plugs Sentry's API directly into your LLM. https://mcp.sentry.dev/mcp",
        "confidence": "fetched",
    },
    71: {
        "one_liner": "Docs and databases with a public REST API.",
        "auth_method": "API key or OAuth2",
        "access_type": "Self-serve",
        "api_surface": "REST",
        "mcp": "None found on the fetched page",
        "buildability_verdict": "Yes",
        "blocker": "Internal connections require a workspace owner and must be shared onto each page. Personal access tokens and public OAuth connections are also documented. An official MCP server was not on this page.",
        "evidence_url": "https://developers.notion.com/guides/get-started/authorization",
        "quote": "Internal connections use a static API token, personal access tokens use a user-scoped static API token, and public connections use the OAuth 2.0 protocol.",
        "confidence": "fetched",
    },
    72: {
        "one_liner": "Spreadsheet-database with a Web API.",
        "auth_method": "Personal access token or OAuth2",
        "access_type": "Self-serve",
        "api_surface": "REST",
        "mcp": "None found on the fetched page",
        "buildability_verdict": "Yes",
        "blocker": "Legacy API keys are dead as of 1 Feb 2024. Use a personal access token or OAuth, both as Bearer.",
        "evidence_url": "https://airtable.com/developers/web/api/authentication",
        "quote": "As of February 1st 2024, the deprecation period for Airtable API keys has ended.",
        "confidence": "fetched",
    },
    73: {
        "one_liner": "Issue tracker with a hosted MCP server.",
        "auth_method": "OAuth2 or API key",
        "access_type": "Self-serve",
        "api_surface": "MCP",
        "mcp": "Official action server at https://mcp.linear.app/mcp",
        "buildability_verdict": "Yes",
        "blocker": "None. OAuth 2.1 with dynamic client registration, or a bearer token / API key. A read-only endpoint exists. GraphQL auth was not the page fetched.",
        "evidence_url": "https://linear.app/docs/mcp",
        "quote": "Read-write access is provided through https://mcp.linear.app/mcp by default. You can also authenticate directly with a bearer token or Linear API key.",
        "confidence": "fetched",
    },
    74: {
        "one_liner": "Atlassian issue tracker with a Cloud REST API.",
        "auth_method": "Basic (email + API token) or OAuth2",
        "access_type": "Self-serve",
        "api_surface": "REST",
        "mcp": "None found on the fetched page",
        "buildability_verdict": "Yes",
        "blocker": "Scripts can use Basic auth with an Atlassian account email and an API token. Password auth is deprecated. Multi-customer apps should use OAuth 2.0 (3LO), not collected API tokens.",
        "evidence_url": "https://developer.atlassian.com/cloud/jira/platform/basic-auth-for-rest-apis/",
        "quote": "Basic auth requires API tokens. You generate an API token for your Atlassian account and use it to authenticate anywhere where you would have used a password.",
        "confidence": "fetched",
    },
    75: {
        "one_liner": "Work-management tool with a public API.",
        "auth_method": "Personal access token, OAuth2, or service account",
        "access_type": "Self-serve",
        "api_surface": "REST",
        "mcp": "None found on the fetched page",
        "buildability_verdict": "Yes",
        "blocker": "A personal access token from the developer console is enough to start. Service accounts are an Enterprise feature. View-only licenses have limited API access.",
        "evidence_url": "https://developers.asana.com/docs/authentication",
        "quote": "A personal access token (PAT) is the quickest and simplest way to authenticate in the API.",
        "confidence": "fetched",
    },
    76: {
        "one_liner": "Work OS with a GraphQL API and a free developer account.",
        "auth_method": "API key or OAuth2",
        "access_type": "Self-serve",
        "api_surface": "GraphQL",
        "mcp": "None found on the fetched page",
        "buildability_verdict": "Yes",
        "blocker": "None. Personal v2 token from the Developer Center. The documented curl sends the raw token in Authorization, not Bearer. A free developer account is linked from the auth page.",
        "evidence_url": "https://developer.monday.com/api-reference/docs/authentication",
        "quote": "If you don't have a monday.com account yet, create a free developer account to get an API token and start testing.",
        "confidence": "fetched",
    },
    77: {
        "one_liner": "Work-management tool with a public REST API.",
        "auth_method": "API key or OAuth2",
        "access_type": "Self-serve",
        "api_surface": "REST",
        "mcp": "None found on the fetched page",
        "buildability_verdict": "Yes",
        "blocker": "Personal tokens (pk_) are self-serve and are sent as Authorization: {token}, not Bearer. OAuth apps can only be created by a workspace owner or admin.",
        "evidence_url": "https://developer.clickup.com/docs/authentication",
        "quote": "For personal use, authenticate with your personal API token. For apps or integrations that other people use, use the OAuth flow.",
        "confidence": "fetched",
    },
    78: {
        "one_liner": "Docs product. The API reference now brands itself Superhuman Docs (formerly Coda).",
        "auth_method": "Not found",
        "access_type": "Could not verify",
        "api_surface": "REST",
        "mcp": "Official MCP guide is linked; the server URL was not in the retrieved chunk",
        "buildability_verdict": "Could not verify",
        "blocker": "REST at https://coda.io/apis/v1 is documented, and an MCP guide is linked. The authentication section was not in the retrieved chunk, so auth and the free-vs-paid rule are not claimed.",
        "evidence_url": "https://coda.io/developers/apis/v1",
        "quote": "The Superhuman Docs API is a RESTful API that lets you programmatically interact with data in Superhuman Docs (formerly Coda).",
        "confidence": "partial",
    },
    79: {
        "one_liner": "Spreadsheet and work-management platform. Auth page 404'd.",
        "auth_method": "Not found",
        "access_type": "Could not verify",
        "api_surface": "Could not verify",
        "mcp": "Could not verify",
        "buildability_verdict": "Could not verify",
        "blocker": "https://developers.smartsheet.com/docs/rest-api-authentication returned 404. No substitute URL was verified.",
        "evidence_url": "https://developers.smartsheet.com/docs/rest-api-authentication",
        "quote": "",
        "confidence": "unverified",
    },
    80: {
        "one_liner": "Time-tracking API.",
        "auth_method": "Personal access token or OAuth2",
        "access_type": "Self-serve",
        "api_surface": "REST",
        "mcp": "None found on the fetched page",
        "buildability_verdict": "Yes",
        "blocker": "None. Personal access tokens are created in Harvest ID, Developers. Other users require an OAuth2 app. Requests also need Harvest-Account-Id.",
        "evidence_url": "https://help.getharvest.com/api-v2/authentication-api/authentication/authentication/",
        "quote": "A Personal Access Token which is tied directly to you and is the quickest way to start playing around with the API.",
        "confidence": "fetched",
    },
    81: {
        "one_liner": "Payments API with an official MCP server in public preview.",
        "auth_method": "API key or OAuth2",
        "access_type": "Self-serve",
        "api_surface": "REST + MCP",
        "mcp": "Official server at https://mcp.stripe.com (public preview)",
        "buildability_verdict": "Yes",
        "blocker": "MCP docs confirm OAuth for interactive clients and API keys for autonomous ones. The classic API authentication reference hit an hCaptcha wall, so the secret-key header format is not quoted from that page.",
        "evidence_url": "https://docs.stripe.com/mcp",
        "quote": "Stripe's MCP server supports two authentication methods: OAuth, and API keys.",
        "confidence": "fetched",
    },
    82: {
        "one_liner": "Bank-connection API with a self-serve sandbox.",
        "auth_method": "API key (client_id + secret)",
        "access_type": "Self-serve to start, gated for production",
        "api_surface": "REST",
        "mcp": "Official MCP toolkit linked from the quickstart (GitHub), not a hosted URL on that page",
        "buildability_verdict": "Conditional",
        "blocker": "Sandbox keys are self-serve from the Dashboard. Production is a separate environment. This pass did not retrieve the production-access application page, so live data stays gated.",
        "evidence_url": "https://plaid.com/docs/quickstart/",
        "quote": "You'll have two different API keys, and there are two different Plaid environments. Today we'll start in the Sandbox environment.",
        "confidence": "fetched",
    },
    83: {
        "one_liner": "Crypto exchange with a public Spot REST API.",
        "auth_method": "Not found",
        "access_type": "Could not verify",
        "api_surface": "REST",
        "mcp": "Could not verify",
        "buildability_verdict": "Could not verify",
        "blocker": "Public market-data REST is documented, including a demo and testnet host. Signed private-endpoint auth was not on the general-endpoints page, so trading auth is not claimed.",
        "evidence_url": "https://developers.binance.com/docs/binance-spot-api-docs/rest-api/general-endpoints",
        "quote": "",
        "confidence": "partial",
    },
    84: {
        "one_liner": "Named product was not found as a public developer portal.",
        "auth_method": "Not found",
        "access_type": "Could not verify",
        "api_surface": "Could not verify",
        "mcp": "Could not verify",
        "buildability_verdict": "Could not verify",
        "blocker": "No official docs for a product named Paygent Connect. NMI (docs.nmi.com) has API keys, but it is a different product and is not used as evidence here.",
        "evidence_url": "",
        "quote": "",
        "confidence": "unverified",
    },
    85: {
        "one_liner": "Payments product whose /docs path 404'd.",
        "auth_method": "Not found",
        "access_type": "Could not verify",
        "api_surface": "Could not verify",
        "mcp": "Could not verify",
        "buildability_verdict": "Could not verify",
        "blocker": "https://www.ipayx.ai/docs returned 404. No public API reference was found. Absence of this path is not a full proof the company has no API.",
        "evidence_url": "https://www.ipayx.ai/docs",
        "quote": "404. Oops! Page not found.",
        "confidence": "unverified",
    },
    86: {
        "one_liner": "Intuit accounting API.",
        "auth_method": "OAuth2",
        "access_type": "Self-serve",
        "api_surface": "REST",
        "mcp": "Could not verify",
        "buildability_verdict": "Conditional",
        "blocker": "The official page is titled Set up OAuth 2.0 and the nav links a sandbox and client-id guide. The procedure text did not render (a compiling placeholder). Treat the sandbox as likely, not quoted.",
        "evidence_url": "https://developer.intuit.com/app/developer/qbo/docs/develop/authentication-and-authorization/oauth-2.0",
        "quote": "",
        "confidence": "partial",
    },
    87: {
        "one_liner": "Accounting API with free OAuth and a paid machine-to-machine option.",
        "auth_method": "OAuth2",
        "access_type": "Self-serve",
        "api_surface": "REST",
        "mcp": "None found on the fetched page",
        "buildability_verdict": "Yes",
        "blocker": "Authorization-code and PKCE flows are free. Custom Connections (client credentials) are a paid add-on and one organisation only. Uncertified apps cap at 25 tenants.",
        "evidence_url": "https://developer.xero.com/documentation/guides/oauth2/overview/",
        "quote": "Code flow: Free. PKCE flow: Free. Custom Connection: Monthly fee on the Xero organisation.",
        "confidence": "fetched",
    },
    88: {
        "one_liner": "Corporate card and spend API.",
        "auth_method": "User token (Bearer)",
        "access_type": "Gated",
        "api_surface": "REST",
        "mcp": "None found on the fetched page",
        "buildability_verdict": "Conditional",
        "blocker": "An account admin or card admin must accept the developer API agreement, then create a user token. There is a production server only (https://api.brex.com). No sandbox was documented on this page.",
        "evidence_url": "https://developer.brex.com/guides/authentication",
        "quote": "Sign in to dashboard.brex.com as an account admin or card admin. If your company has not accepted the developer API agreement, these must be accepted to use the developer API.",
        "confidence": "fetched",
    },
    89: {
        "one_liner": "Corporate card and bill-pay API.",
        "auth_method": "OAuth2",
        "access_type": "Gated",
        "api_surface": "REST",
        "mcp": "None found on the fetched page",
        "buildability_verdict": "Conditional",
        "blocker": "Client-credentials (no user interaction) or authorization code. The resource owner is a Ramp business. A public developer signup independent of a Ramp account was not on this page.",
        "evidence_url": "https://docs.ramp.com/developer-api/v1/authorization",
        "quote": "Ramp uses OAuth 2.0 for secure API access. Client Credentials: internal integrations, server-to-server. Authorization Code: third-party apps.",
        "confidence": "fetched",
    },
    90: {
        "one_liner": "Private-markets data. No public developer portal was retrieved.",
        "auth_method": "Not found",
        "access_type": "Could not verify",
        "api_surface": "Could not verify",
        "mcp": "Could not verify",
        "buildability_verdict": "Could not verify",
        "blocker": "No official developer-docs page was retrieved. Do not treat secondary Postman collections as the contract.",
        "evidence_url": "",
        "quote": "",
        "confidence": "unverified",
    },
    91: {
        "one_liner": "Notebook product. The public API is the enterprise Google Cloud API, not consumer NotebookLM.",
        "auth_method": "Google Cloud access token",
        "access_type": "Gated",
        "api_surface": "REST",
        "mcp": "None found on the fetched page",
        "buildability_verdict": "Conditional",
        "blocker": "notebooks.create requires a GCP project, a Gemini Notebook Enterprise setup, and licenses. Auth is Authorization: Bearer from gcloud. Consumer NotebookLM is not this API.",
        "evidence_url": "https://docs.cloud.google.com/gemini/enterprise/notebooklm-enterprise/docs/api-notebooks",
        "quote": "Get licenses for Gemini Notebook Enterprise. Authorization:Bearer $(gcloud auth print-access-token)",
        "confidence": "fetched",
    },
    92: {
        "one_liner": "Meeting notes with an official MCP server.",
        "auth_method": "OAuth2",
        "access_type": "Self-serve",
        "api_surface": "MCP",
        "mcp": "Official action server at https://mcp.otter.ai/mcp",
        "buildability_verdict": "Yes",
        "blocker": "A user authorizes the Otter account. A REST API was not on this help article. Plan limits were not stated.",
        "evidence_url": "https://help.otter.ai/hc/en-us/articles/35287607569687-Otter-MCP-Server",
        "quote": "All access is OAuth-authenticated with granular permissions. url: https://mcp.otter.ai/mcp",
        "confidence": "fetched",
    },
    93: {
        "one_liner": "Meeting recorder with a REST API.",
        "auth_method": "API key",
        "access_type": "Self-serve",
        "api_surface": "REST",
        "mcp": "None found on the fetched page",
        "buildability_verdict": "Yes",
        "blocker": "API keys are generated in the Fathom website settings. OAuth is mentioned only as a rate-limited token endpoint, not fully specified on this page. Plan gate was not stated.",
        "evidence_url": "https://developers.fathom.ai/api-overview",
        "quote": "All REST API resources are authenticated with API keys generated via the Fathom website's settings area.",
        "confidence": "fetched",
    },
    94: {
        "one_liner": "Research search with an MCP server. A shared API key is an Enterprise credential.",
        "auth_method": "API key or OAuth2",
        "access_type": "Gated",
        "api_surface": "MCP",
        "mcp": "Official server at https://mcp.consensus.app/mcp",
        "buildability_verdict": "Conditional",
        "blocker": "Per-user OAuth exists, but the server-side API key maps to the Enterprise tier. Confidential OAuth clients are provisioned by sales. One tool: search.",
        "evidence_url": "https://docs.consensus.app/enterprise/connection-reference",
        "quote": "A single opaque credential sent as a bearer token. It maps to your Enterprise tier.",
        "confidence": "fetched",
    },
    95: {
        "one_liner": "Document parsing API with a free studio account, REST, and MCP.",
        "auth_method": "API key",
        "access_type": "Self-serve",
        "api_surface": "REST + MCP",
        "mcp": "Official MCP documented on the agent guide",
        "buildability_verdict": "Yes",
        "blocker": "None to start. Free account at studio.reducto.ai, then Authorization: Bearer. Credits apply after the free path; a sales contract is not required to get a key.",
        "evidence_url": "https://docs.reducto.ai/agent-guide",
        "quote": "Create a free account at studio.reducto.ai. Auth: Authorization: Bearer $REDUCTO_API_KEY.",
        "confidence": "fetched",
    },
    96: {
        "one_liner": "Coding agent with a session API. Devin consumes MCP; this page does not publish a Devin MCP server.",
        "auth_method": "Service-user API key or personal access token",
        "access_type": "Gated",
        "api_surface": "REST",
        "mcp": "Devin is an MCP client on the fetched docs, not a confirmed MCP server",
        "buildability_verdict": "Conditional",
        "blocker": "Bearer tokens use the cog_ prefix. Keys are created in a Devin organization. A free tier was not stated on the auth page. Enterprise PATs are disabled by default.",
        "evidence_url": "https://docs.devin.ai/api-reference/authentication",
        "quote": "Include your token in the Authorization header of every request: Authorization: Bearer cog_your_token_here.",
        "confidence": "fetched",
    },
    97: {
        "one_liner": "Media generation API, pay-as-you-go.",
        "auth_method": "API key pair",
        "access_type": "Self-serve",
        "api_surface": "REST",
        "mcp": "Not on the fetched FAQ page",
        "buildability_verdict": "Yes",
        "blocker": "Create an account at the console and generate credentials. Header is Authorization: Key KEY_ID:KEY_SECRET, not Bearer. Billing is pay-as-you-go; invoice billing is a sales conversation.",
        "evidence_url": "https://docs.higgsfield.ai/docs/help/faq",
        "quote": "Send requests to https://api.higgsfield.ai and authenticate server-side with Authorization: Key YOUR_KEY_ID:YOUR_KEY_SECRET.",
        "confidence": "fetched",
    },
    98: {
        "one_liner": "Local diagram renderer. No hosted API was in the retrieved page.",
        "auth_method": "Not found",
        "access_type": "Could not verify",
        "api_surface": "Could not verify",
        "mcp": "Could not verify",
        "buildability_verdict": "Could not verify",
        "blocker": "The mermaid-cli repository returned HTTP 200, but the retrieved text was GitHub chrome, not a README or an API reference. No remote API is claimed.",
        "evidence_url": "https://github.com/mermaid-js/mermaid-cli",
        "quote": "",
        "confidence": "partial",
    },
    99: {
        "one_liner": "YouTube transcript and metadata API (TranscriptAPI).",
        "auth_method": "API key",
        "access_type": "Self-serve",
        "api_surface": "REST",
        "mcp": "None found on the fetched page",
        "buildability_verdict": "Yes",
        "blocker": "None to start. Bearer key from the dashboard. Calls spend credits; some metadata endpoints are free.",
        "evidence_url": "https://transcriptapi.com/docs/api/",
        "quote": "The API uses Bearer token authentication. Include your API key in the Authorization header of every request.",
        "confidence": "fetched",
    },
    100: {
        "one_liner": "Meeting recorder with a public REST API.",
        "auth_method": "Personal access token",
        "access_type": "Self-serve",
        "api_surface": "REST",
        "mcp": "None found on the fetched page",
        "buildability_verdict": "Yes",
        "blocker": "Create a PAT in Grain settings. Send Authorization: Bearer and a Public-Api-Version header. A plan gate was not on the overview. Other auth methods exist on a linked page that was not fetched.",
        "evidence_url": "https://developers.grain.com/",
        "quote": "A Personal Access Token (PAT) authenticates requests as you, with the same access you have in Grain.",
        "confidence": "fetched",
    },
}
